Script started on 2021-09-08 23:18:13+00:00 [TERM="screen" TTY="/dev/pts/0" COLUMNS="318" LINES="79"]
Initialize dynamodb
Table already exists
Testing write data of size 4
Expected write size 4, input data size: 4
Testing read data of size 4
Expected read size 4, output data size: 4
Testing write data of size 8
Expected write size 8, input data size: 8
Testing read data of size 8
^CTraceback (most recent call last):
  File "benchmark.py", line 181, in <module>
    results, read_capacity = test_dynamodb_read(client, f"size_{size}", size, args.repetitions)
  File "benchmark.py", line 72, in test_dynamodb_read
    ret = client.get_item(
  File "/home/ubuntu/data/python-venv/lib/python3.8/site-packages/botocore/client.py", line 276, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ubuntu/data/python-venv/lib/python3.8/site-packages/botocore/client.py", line 572, in _make_api_call
    http, parsed_response = self._make_request(
  File "/home/ubuntu/data/python-venv/lib/python3.8/site-packages/botocore/client.py", line 592, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/ubuntu/data/python-venv/lib/python3.8/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/ubuntu/data/python-venv/lib/python3.8/site-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/home/ubuntu/data/python-venv/lib/python3.8/site-packages/botocore/endpoint.py", line 115, in create_request
    self._event_emitter.emit(event_name, request=request,
  File "/home/ubuntu/data/python-venv/lib/python3.8/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/ubuntu/data/python-venv/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/ubuntu/data/python-venv/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/ubuntu/data/python-venv/lib/python3.8/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/home/ubuntu/data/python-venv/lib/python3.8/site-packages/botocore/signers.py", line 160, in sign
    auth.add_auth(request)
  File "/home/ubuntu/data/python-venv/lib/python3.8/site-packages/botocore/auth.py", line 363, in add_auth
    canonical_request = self.canonical_request(request)
  File "/home/ubuntu/data/python-venv/lib/python3.8/site-packages/botocore/auth.py", line 310, in canonical_request
    body_checksum = self.payload(request)
  File "/home/ubuntu/data/python-venv/lib/python3.8/site-packages/botocore/auth.py", line 271, in payload
    request_body = request.body
  File "/home/ubuntu/data/python-venv/lib/python3.8/site-packages/botocore/awsrequest.py", line 466, in body
    @property
KeyboardInterrupt

Script done on 2021-09-08 23:18:29+00:00 [COMMAND_EXIT_CODE="130"]
